/**
 * generated by Xtext 2.30.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com) and others.
 */
package com.epistimis.uddl.uddl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Logical Boolean</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.epistimis.uddl.uddl.UddlPackage#getLogicalBoolean()
 * @model
 * @generated
 */
public interface LogicalBoolean extends LogicalValueType
{
} // LogicalBoolean
